---
# tasks/main.yml

- name: "check {{ desktop_img_path }} exists"
  stat: "path={{ desktop_img_path }}"
  when: desktop_img_path is defined
  register: img_exists

- name: run set_desktops.py
  command: "{{ desktop_exec }} --path {{ desktop_img_path }}"
  when: img_exists.stat.exists == true
