---
# tasks/url_img.yml

- name: "download {{ desktop_img_path }}"
  get_url: "url={{ desktop_img_path }} dest={{ local_img_path }}"

#- name: "check if {{ local_img_path }} exists"
#  stat: "path={{ local_img_path }}"
#  when: "desktop_img_path is defined and desktop_img_path|search('^http') == true"
#  register: img_exists

- name: run set_desktops.py to set desktop image
  command: "{{ desktops_exec }} --path {{ local_img_path }}"
#  when: img_exists.stat.exists == true
#  when: "desktop_img_path is defined and desktop_img_path|search('^http') == true"