---
# git clone, backup existing and then copy in place my dotfiles!
- name: git dat dots repo yo
  git: repo=ssh://tusk.ninjabong.com/home/juan/repo/dotfiles.git
       dest=~/src/repo/dotfiles
       accept_hostkey=yes
       ssh_opts="-o Port=42022"

- name: copy dot bash
  ignore_errors: True
  copy: src=~/src/repo/dotfiles/bash/osx_bash_profile
        dest=~/.bash_profile
        owner=juan
        group=staff
        mode=644
        backup=yes

- name: copy dot git
  ignore_errors: True
  copy: src=~/src/repo/dotfiles/git/osx_ninjabong_cfg
        dest=~/.gitconfig
        owner=juan
        group=staff
        mode=644
        backup=yes

- name: copy dot ssh config
  ignore_errors: True
  copy: src=~/src/repo/dotfiles/ssh/ssh_config
        dest=~/.ssh/config
        owner=juan
        group=staff
        mode=600
        backup=yes

- name: copy dot irssi stuffs
  ignore_errors: True
  copy: src=~/src/repo/dotfiles/irssi/
        dest=~/.irssi
        owner=juan
        group=staff
        directory_mode=700
        mode=700
        backup=yes

- name: copy dot silc stuffs
  ignore_errors: True
  copy: src=~/src/repo/dotfiles/silc/
        dest=~/.silc
        owner=juan
        group=staff
        directory_mode=700
        mode=700
        backup=yes
