---
# creates/updates a munki manifest from given pkg_list (for autopkg)

- name: Check if manifest {{ manifest_name }} exists
  stat: path={{ repo_path }}/manifests/{{ manifest_name }} follow=true
  register: manifest_exists

- name: Create new munki manifest {{ manifest_name }}
  command: "{{ manifestutil_exec }} new-manifest {{ manifest_name }}"
  when: manifest_exists.stat.exists == false

- name: Add items to munki manifest {{ manifest_name }}
  command: "{{ manifestutil_exec }} add-pkg {{ item }} --manifest {{ manifest_name }} --section optional_installs"
  with_items: pkg_list
