---

- name: Defaults write settings to ManagedInstalls.plist
  sudo: True
  command: "{{ defaults_mngdprefs_write }} {{ item.pref }}"
  with_items:
    - { pref: '"AdditionalHttpHeaders" -array "{{ AdditionalHttpHeaders }}"' }
    - { pref: '"AppleSoftwareUpdatesOnly" -bool {{ AppleSoftwareUpdatesOnly }}' }
    - { pref: '"CatalogURL" -string "{{ CatalogURL }}"' }
    - { pref: '"ClientCertificatePath" -string "{{ ClientCertificatePath }}"' }
    - { pref: '"ClientKeyPath" -string "{{ ClientKeyPath }}"' }
    - { pref: '"ClientIdentifier" -string "{{ ClientIdentifier }}"' }
    - { pref: '"CurlPath" -string "{{ CurlPath }}"' }
    - { pref: '"DaysBetweenNotifications" -int "{{ DaysBetweenNotifications }}"' }
    - { pref: '"InstallAppleSoftwareUpdates" -bool {{ InstallAppleSoftwareUpdates }}' }
    - { pref: '"InstallRequiresLogout" -bool {{ InstallRequiresLogout }}' }
    - { pref: '"LoggingLevel" -int "{{ LoggingLevel }}"' }
    - { pref: '"LogFile" -string "{{ LogFile }}"' }
    - { pref: '"LogToSyslog" -bool {{ LogToSyslog }}' }
    - { pref: '"ManagedInstallDir" -string "{{ ManagedInstallDir }}"' }
    - { pref: '"ManifestURL" -string "{{ ManifestURL }}"' }
    - { pref: '"ManifestBaseURL" -string "{{ ManifestURL }}"' }
    - { pref: '"PackageURL" -string "{{ PackageURL }}"' }
    - { pref: '"SoftwareRepoCAPath" -string "{{ SoftwareRepoCAPath }}"' }
    - { pref: '"SoftwareRepoCACertificate" -string "{{ SoftwareRepoCACertificate }}"' }
    - { pref: '"SoftwareRepoURL" -string "{{ SoftwareRepoURL }}"' }
    - { pref: '"SuppressUserNotification" -bool {{ SuppressUserNotification }}' }
    - { pref: '"SuppressAutoInstall" -bool {{ SuppressAutoInstall }}' }
    - { pref: '"SuppressLoginwindowInstall" -bool {{ SuppressLoginwindowInstall }}' }
    - { pref: '"SuppressStopButtonOnInstall" -bool {{ SuppressStopButtonOnInstall }}' }
    - { pref: '"ShowRemovalDetail" -bool {{ ShowRemovalDetail }}' }
    - { pref: '"SuppressAutoInstall" -bool {{ SuppressAutoInstall }}' }
    - { pref: '"SuppressUserNotification" -bool {{ SuppressUserNotification }}' }
    - { pref: '"UseClientCertificate" -bool {{ UseClientCertificate }}' }
