---

- name: "Create the repo directories in {{ repo_path }}"
  file: path={{ item }}
        mode=755
        recurse=yes
        state=directory
  with_items:
    - "{{ repo_path }}/catalogs"
    - "{{ repo_path }}/client_resources"
    - "{{ repo_path }}/icons"
    - "{{ repo_path }}/manifests"
    - "{{ repo_path }}/pkgs"
    - "{{ repo_path }}/pkgsinfo"


- name: Check for OS X Server
  stat: path=/Library/Server/Web/Data/Sites/Default
  register: is_osx_server

- name: "Symlink {{ repo_path }} to Apache's default DocumentRoot for OS X Server"
  sudo: True
  file: src={{ repo_path }}
        dest=/Library/Server/Web/Data/Sites/Default/{{ repo_path | basename }}
        owner=root group=wheel
        state=link
  when: is_osx_server.stat.exists == true

- name: "Symlink {{ repo_path }} to Apache's default DocumentRoot for OS X Client"
  sudo: True
  file: src={{ repo_path }}
        dest=/Library/Webserver/Documents/{{ repo_path | basename }}
        owner=root group=wheel
        state=link
  when: is_osx_server.stat.exists == false


- name: (Re)Start Apache
  sudo: True
  command: /usr/sbin/apachectl restart
