---
# Finder's Preferences, normally set via cmd-; in Finder
# playbook use:
#  - role: finder_prefs
# - First Page
#    show_internal: [on|off]
#    show_extensions: [on|off]
#    show_external: [on|off]
#    show_removeable: [on|off]
#    show_servers: [on|off]
#    new_window: [machine|bootdisk|home|desktop|documents|allfiles|custom*]
#    new_window_path: "path relative to /" *only needed when new_window = custom
#    always_new: [on|off]
#    spring_loaded_folders: [on|off]
#    spring_loaded_delay: [0.0-1.0] (seconds)
# - Third Page
#    sidebar: [on|off]
#    sidebar_width: []##]
#    sidebar_devices: [on|off]
#    sidebar_favorites: [on|off]
#    sidebar_shared: [on|off]
#    sidebar_tags: [on|off]
# - Fourth Page
#    show_extensions: [on|off]
#    extension_warning: [on|off]
#    trash_warning: [on|off]
#    trash_securely: [on|off]
#    search_default: [mac|current|previous]


# before we do anything, backup existing Finder preferences
- name: back up existing Finder prefs
  copy: src={{ finder_plist }} dest=~/Library/Preferences/com.apple.finder.osxc_backup.plist mode=0600 backup=yes

# First tab - General "GNRL"
# Show these items on the desktop:
- name: set Hard disks visibility to {{ show_internal }}
  command: "{{ defaults_finder_write }} ShowHardDrivesOnDesktop -bool {{ show_internal }}"

- name: set External disks visibility to {{ show_external }}
  command: "{{ defaults_finder_write }} ShowExternalHardDrivesOnDesktop -bool {{ show_external }}"

- name: set CDs, DVDs, and iPods visibility to {{ show_removeable }}
  command: "{{ defaults_finder_write }} ShowRemovableMediaOnDesktop -bool {{ show_removeable }}"

- name: set Connected servers visibility to {{ show_servers }}
  command: "{{ defaults_finder_write }} ShowMountedServersOnDesktop -bool {{ show_servers }}"

# New Finder windows show:
- name: set default Finder window to {{ ansible_nodename }}
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfCm"
  when: new_window == "machine"

- name: set default Finder window path to {{ ansible_nodename }}
  command: "{{ defaults_finder_del }} com.apple.finder NewWindowTargetPath"
  when: new_window == "machine"

- name: set default Finder window to /
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfVo"
  when: new_window == "bootdisk"

- name: set default Finder window path to /
  command: "{{ defaults_finder_write }} NewWindowTargetPath -string file://localhost/"
  when: new_window == "bootdisk"

- name: set default Finder window to ~/
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfHm"
  when: new_window == "home"

- name: set default Finder window path to ~/
  command: "{{ defaults_finder_write }} NewWindowTargetPath -string file://localhost/Users/{{ ansible_env.USER}}/"
  when: new_window == "home"

- name: set default Finder window to ~/Desktop
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfDe"
  when: new_window == "desktop"

- name: set default Finder window path to ~/Desktop
  command: "{{ defaults_finder_write }} NewWindowTargetPath -string file://localhost/Users/{{ ansible_env.USER}}/Desktop/"
  when: new_window == "desktop"

- name: set default Finder window to ~/Documents
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfDo"
  when: new_window == "documents"

- name: set default Finder window path to ~/Documents
  command: "{{ defaults_finder_write }} NewWindowTargetPath -string file://localhost/Users/{{ ansible_env.USER}}/Documents/"
  when: new_window == "documents"

- name: set default Finder window to All Files
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfAF"
  when: new_window == "allfiles"

- name: set default Finder window path to All Files
  command: "{{ defaults_finder_write }} NewWindowTargetPath -string file://localhost/System/Library/CoreServices/Finder.app/Contents/Resources/MyLibraries/myDocuments.cannedSearch"
  when: new_window == "allfiles"

- name: set default Finder window to Other
  command: "{{ defaults_finder_write }} NewWindowTarget -string PfLo"
  when: new_window == "custom"

- name: set default Finder window path to All Files
  command: "{{ defaults_finder_write }} NewWindowTargetPath -string file://localhost/{{ new_window_path }}/"
  when: new_window == "custom"


# Always opens folders in a new window (10.8)
- name: set Always opens folders in a new window to {{ always_new }}
  command: "{{ defaults_finder_write }} FinderSpawnWindow -bool {{ always_new }}"
  when: "ansible_distribution_version | search('10.8')"

# Open folders in tabs instead of new window (10.9)
- name: set Open folders in tabs instead of new windows to {{ always_new }}
  command: "{{ defaults_finder_write }} FinderSpawnTab -bool {{ always_new }}"
  when: "ansible_distribution_version | search('10.9')"


# Spring-loaded folders
- name: setting Spring-loaded folders to {{ spring_loaded_folders }}
  command: "{{ defaults_global_write }} com.apple.springing.enabled -bool {{ spring_loaded_folders }}"

- name: setting Spring-loaded folders and windows delay time to {{ spring_loaded_delay }}
  command: "{{ defaults_global_write }} com.apple.springing.delay -float {{ spring_loaded_delay }}"
  when: spring_loaded_folders == True


# Second tab - Labels "LBLS" in 10.8.x / "TAGS" in 10.9.x
# its complex enough to warrant its own seperate role
# see http://rdr.to/0tZ


# Third tab - Sidebar "SDBR"
# show Sidebar is a View menu setting, not from prefs, but fits here logically
# Finder: show Sidebar
- name: setting show Sidebar to {{ sidebar }}
  command: "{{ defaults_finder_write }} ShowSidebar -bool {{ sidebar }}"

- name: setting Sidebar width to {{ sidebar_width }}
  command: "{{ defaults_finder_write }} SidebarWidth -int {{ sidebar_width }}"

# Finder: Sidebar options
- name: setting Devices in Sidebar to {{ sidebar_devices }}
  command: "{{ defaults_finder_write }} SidebarDevicesSectionDisclosedState -bool {{ sidebar_devices }}"

- name: setting Favorites in Sidebar to {{ sidebar_favorites }}
  command: "{{ defaults_finder_write }} SidebarPlacesSectionDisclosedState -bool {{ sidebar_favorites }}"

- name: setting Shared in Sidebar to {{ sidebar_shared }}
  command: "{{ defaults_finder_write }} SidebarSharedSectionDisclosedState -bool {{ sidebar_shared }}"

# Tags are 10.9 only
- name: setting Recent Tags in Sidebar to {{ sidebar_tags }}
  command: "{{ defaults_finder_write }} ShowRecentTags -bool {{ sidebar_tags }}"
  when: "ansible_distribution_version | search('10.9')"


# Fourth tab - Advanced "ADVD"
# filename extensions related options
- name: setting Show all filename extensions to {{ show_extensions }}
  command: "{{ defaults_global_write }} AppleShowAllExtensions -bool {{ show_extensions }}"

- name: setting Show warning before changing an extension to {{ extension_warning }}
  command: "{{ defaults_finder_write }} FXEnableExtensionChangeWarning -bool {{ extension_warning }}"

# Trash related options
- name: setting Show warning before emptying the Trash to {{ trash_warning }}
  command: "{{ defaults_finder_write }} WarnOnEmptyTrash -bool {{ trash_warning }}"

- name: setting Empty Trash securely to {{ trash_securely }}
  command: "{{ defaults_finder_write }} EmptyTrashSecurely -bool {{ trash_securely }}"

# When performing a search:
# absent by default, auto uses SCev until set to SCcf of SCsp, then sets SCev if/when chosen later
- name: set "When performing a search" to "Search This Mac"
  command: "{{ defaults_finder_write }} FXDefaultSearchScope -string SCev"
  when: search_default == "mac"

- name: set "When performing a search" to "Search the Current Folder"
  command: "{{ defaults_finder_write }} FXDefaultSearchScope -string SCcf"
  when: search_default == "current"

- name: set "When performing a search" to "Use the Previous Search Scope"
  command: "{{ defaults_finder_write }} FXDefaultSearchScope -string SCsp"
  when: search_default == "previous"


# changes made, now let's make them active
- name: killing and restarting Finder
  command: "/usr/bin/killall Finder > /dev/null 2>&1"
 