---
- hosts: all
  roles:

  ## my dotfiles, not yours - myne.
  - role: dots
  ## brew, then cask, then osx bits like the dock which need the cask to go first
  # brew stuff
  ## some old reliables
  - role: brew_package
    package_name: tree
  ## wget
  - role: brew_package
    package_name: wget
  ## figlet!
  - role: brew_package
    package_name: figlet
  ## irc!
  - role: brew_package
    package_name: irssi
# broken 8/
#  - role: brew_package
#    package_name: silc-client
  ## some networky stuffs
  - role: brew_package
    package_name: mtr
  - role: brew_package
    package_name: nmap
  - role: brew_package
    package_name: whatmask

  # cask stuff... for the apps
  ## Misc Stuff...
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: musicmanager
  - role: cask_package
    package_name: flip4mac
  - role: cask_package
    package_name: vlc
  ## Misc Things...
  - role: cask_package
    package_name: asepsis
  - role: cask_package
    package_name: box-sync
  - role: cask_package
    package_name: flux
  - role: cask_package
    package_name: istat-menus
  - role: cask_package
    package_name: pacifist
  - role: cask_package
    package_name: totalterminal
  - role: cask_package
    package_name: osxfuse
  - role: cask_package
    package_name: sshfs
  ## Text Editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: sublime-text
  - role: cask_package
    package_name: textmate
  ## VM related stuff
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vmware-fusion
  - role: cask_package
    package_name: vagrant
  ## Panic, mmmmm Panic
  - role: cask_package
    package_name: transmit
  - role: cask_package
    package_name: panic-unison

  # osx config
  ## kill the dashboard
  - role: dashboard
    disabled: YES
  ## fix up the dock
  - role: dock
    apps:
    - /Applications/"System Preferences.app"
    - /Applications/Utilities/Terminal.app
    - /Applications/"Google\ Chrome.app"
    - /Applications/"Sublime\ Text\ 2.app"
    - /Applications/TextMate.app
    - /Applications/Utilities/"Managed Software Update.app"
    folders:
    - path: ~/src/github.com
    - path: ~/Downloads
      sort: datemodified
      view: grid
