---
- hosts: all
  roles:

  # osx config
  ## kill the dashboard
  - role: dashboard
    disabled: YES
  ## fix up the dock
  - role: dock
    apps:
    - /Applications/"System Preferences.app"
    - /Applications/Utilities/Terminal.app
    - /Applications/TextMate.app
    - /Applications/Utilities/"Managed Software Update.app"
    folders:
    - path: ~/src/github.com
    - path: ~/Downloads
      sort: datemodified
      view: grid
  ##
  - role: git
    git_user_name: ninjabong
    git_user_email: ninja@ninjabong.com
  - role: legit
  - role: hub

  # brew stuff... for the cli
  ## some old reliables
  - role: brew_package
    package_name: tree
  ## wget
  - role: brew_package
    package_name: wget
  ## figlet!
  - role: brew_package
    package_name: figlet
  ## irc!
  - role: brew_package
    package_name: irssi
# broken 8/
#  - role: brew_package
#    package_name: silc-client
  ## some networky stuffs
  - role: brew_package
    package_name: mtr
  - role: brew_package
    package_name: nmap
  - role: brew_package
    package_name: whatmask

  # cask stuff... for the apps
  ## Asepsis deals with .DS_Store file messes
  - role: cask_package
    package_name: asepsis
  ## TotalTerminal
  - role: cask_package
    package_name: totalterminal
  ## TextMate
  - role: cask_package
    package_name: textmate
  ## OSXFuse + sshFS
  - role: cask_package
    package_name: osxfuse
  - role: cask_package
    package_name: sshfs
