---
## some basic bits to get a fresh machine minimally useable
- hosts: all
  roles:

  - role: computername
    computername: sakura

  - role: sshd
    sshd: "on"

  - role: datetime
    time_zone: Europe/Stockholm

  - role: desktop_image
    desktop_img_path: "http://static.simpledesktops.com/uploads/desktops/2014/06/08/PixelYosemite.png"


  # System Preferences - General
  - role: systemprefs_general
    system_appearance: graphite
    highlight_color: "1.000000 0.874510 0.701961"
    sidebar_icon_size: medium
    scrollbar: Automatic
    scroll_behavior: page
    close_confirms_changes: no
    restore_windows: no
    kb_ui_mode: all
    # only works for 10.10
    #interface_style: Dark

  - role: unhide_library

  - role: homebrew

  - name: homebrew cask
    homebrew: name=caskroom/cask/brew-cask state=present

  - homebrew_tap: tap=caskroom/fonts state=present

  - name: Install casks
    homebrew_cask: name="{{ item }}" state=present
    with_items:
      - alfred
      - iterm2
      - font-inconsolata
      - font-source-code-pro
      - font-terminus

  - role: dock
    apps:
    - "/Applications/System Preferences.app"
    - /Applications/Utilities/iTerm2.app
    - /Applications/Safari.app
    folders:
    - path: ~/src/github.com
      view: grid
    - path: ~/Downloads
      sort: datemodified
      view: grid
