---
## some basic bits to get a fresh machine minimally useable
- hosts: all
  roles:

  - role: computername
    computername: sakura

  - role: sshd
    sshd: "on"

  - role: datetime
    time_zone: Europe/Stockholm

  - role: desktop_image
    desktop_img_path: "http://static.simpledesktops.com/uploads/desktops/2014/06/08/PixelYosemite.png"

  - role: googlefonts
    fonts:
      - inconsolata
      - sourcecodepro

  - role: unhide_library

  - role: homebrew

  - name: homebrew cask
    homebrew: name=caskroom/cask/brew-cask state=present

  - name: Install casks
    homebrew_cask: name="{{ item }}" state=present
    with_items:
      - alfred
      - iterm2

  - role: dock
    apps:
    - "/Applications/System Preferences.app"
    - /Applications/Utilities/iTerm2.app
    - /Applications/Safari.app
    folders:
    - path: ~/src/github.com
      view: grid
    - path: ~/Downloads
      sort: datemodified
      view: grid
