---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Firefox.app
    - /Applications/Airmail.app
    - /Applications/Dashlane.app
    - /Applications/Spotify.app
    - /Applications/Atom.app
    - /Applications/iTerm.app
    - /Applications/Dash.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES
  - role: cask_package
    package_name: flux
  - role: cask_package
    package_name: gfxcardstatus

  # cli
  # shell tooling
  - role: git
    git_user_name: Robin Ricard
    git_user_email: ricard.robin@gmail.com
  - role: oh_my_zsh
  - role: maximum_awesome
  ## languages
  - role: rbenv
  - role: cask_package
    package_name: java

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: intellij-idea

  ## tooling
  - role: cask_package
    package_name: dashlane
  - role: cask_package
    package_name: spectacle
  - role: alfred
  - role: cask_package
    package_name: istat-menus

  ## dev tools
  - role: cask_package
    package_name: github
  - role: cask_package
    package_name: ksdiff

  ## browsers
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: chromium

  ## entertainment
  - role: cask_package
    package_name: vlc
  - role: cask_package
    package_name: spotify
