---
- hosts: all
  roles:
  
  # command-line tools
  - role: common/git
    git_user_name: Robin Ricard
    git_user_email: ricard.robin@gmail.com
  
  # developer software
  - role: common/cask_package
    package_name: atom
