---
- hosts: all
  roles:

  - role: finder_prefs
# - First tab
    show_internal: on
    show_external: true
    show_removeable: on
    show_servers: yes
    new_window: home
    #    new_window_path: /path/to/foo
    always_new: on
    spring_loaded_folders: on
    spring_loaded_delay: 0.33
    # third tab
    sidebar: on
    sidebar_width: 190
    sidebar_devices: on
    sidebar_favorites: on
    sidebar_shared: on
    sidebar_tags: off
    # fourth tab
    show_extensions: on
    extension_warning: off
    trash_warning: off
    trash_securely: off
    search_default: mac

  - role: systemprefs_general
    system_appearance: blue
    highlight_color: "1.000000 0.823500 0.505900"
    sidebar_icon_size: medium
    scrollbar: Automatic
    scroll_behavior: page
    close_confirms_changes: no
    restore_windows: no

  # various sleep related options
  - role: sleep
    system_sleep: "off"
    comp_sleep: "off"
    disk_sleep: "off"
    display_sleep: "15"
    button_sleep: "on"
    wake_on_lan: "on