---
- hosts: all
  roles:

#### custom role to set user image, requires jpg
  ## copy yours to roles/user_image/files/$image_name and then define image_name
  - role: user_image
    image_name: ninjastar.jpg
####
