---
# determining osx version from ansible's variables
# playbook use:
# - role: check_os_vers

- name: checking for Mavericks
  debug: msg="you have Mavericks!"
  when: "ansible_distribution_version | search('10.9')"

- name: checking for Mt. Lion
  debug: msg="you have Mt. Lion!"
  when: "ansible_distribution_version | search('10.8')"
