---
# acquire and install/update latest munki client

- name: Determine if munki is already installed
  stat: path=/usr/local/munki follow=true
  register: munki_exists

- include: pkg.yml
  when: install_type == "pkg" and (update == true or munki_exists.stat.exists == false)

- include: dmg.yml
  when: install_type == "dmg" and (update == true or munki_exists.stat.exists == false)

# update munkitools prefs

- name: Check if munkitools prefs exists
  stat: path={{ munkitools_prefs }} follow=true
  register: munki_prefs_exists

- name: Set munkitools prefs values
  command: /usr/bin/defaults write {{ munkitools_prefs }} {{ item.key }} {{ item.val }}
  with_items:
    - { key: "default_catalog"   , val: "{{ default_catalog }}" }
    - { key: "editor"            , val: "{{ editor }}" }
    - { key: "pkginfo_extension" , val: "{{ pkginfo_extension }}" }
    - { key: "repo_path"         , val: "{{ repo_path }}" }
    - { key: "repo_url"          , val: "{{ repo_url }}" }
  when: update == true or munki_prefs_exists.stat.exists == false

- name: Ensure munkitools prefs plist is XML
  command: /usr/bin/plutil -convert xml1 {{ munkitools_prefs }}
