---
# Desktop's View Options, normally set via cmd-j in Finder
# playbook use:
#  - role: desktop_view_opts
#    arrange_by:
# [none|grid|name|kind|dateModified|dateCreated|dateLastOpened|dateAdded|size|label*]
# * 'label' is for 'Labels' in 10.8 and also 'Tags' in 10.9
#    grid_spacing: [0-100]
#    desktop_icon_size: [16-128]
#    label_on_bottom: [on|off]
#    show_info: [on|off]
#    show_preview: [on|off]
#    text_size: [10-16]
#    toolbar_mode: [1-3]
#    toolbar_shown: [0|1]

# before we do anything, backup existing Finder preferences
- name: back up existing Finder prefs
  copy: "src={{ finder_plist }} dest=~/Library/Preferences/com.apple.finder.osxc_backup.plist mode=0600 backup=yes"



# Change some things
- name: set Desktop Sort by to {{ arrange_by }}
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:arrangeBy string {{ arrange_by }}' {{ finder_plist }}"
# 0-100
- name: set Desktop Grid spacing to {{ grid_spacing }}
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:gridSpacing integer {{ grid_spacing }}' {{ finder_plist }}"
# 16-128
- name: set Desktop Icon size to {{ icon_size }}
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:iconSize integer {{ desktop_icon_size }}' {{ finder_plist }}"

# 0 = right, 1 = bottom
- name: set Desktop Label position to Bottom
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:labelOnBottom bool true' {{ finder_plist }}"
  when: label_on_bottom == "on"

- name: set Desktop Label position to Right
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:labelOnBottom bool false' {{ finder_plist }}"
  when: label_on_bottom == "off"

- name: set Desktop Item info to {{ show_info }}
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:showItemInfo bool {{ show_info }}' {{ finder_plist }}"

- name: set Desktop Show Preview to {{ show_preview }}
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:showIconPreview bool {{ show_preview }}' {{ finder_plist }}"

- name: set Desktop Text size to {{ text_size }}
  command: "{{ plistbuddy_exec }} 'Set :DesktopViewSettings:IconViewSettings:textSize integer {{ text_size }}' {{ finder_plist }}"



# explicitly rewrites the array's dictionary
#     "NSToolbar Configuration Browser" =     {
#         "TB Display Mode" = [1|2|3];
#         "TB Icon Size Mode" = 1;
#         "TB Is Shown" = [0|1];
#         "TB Size Mode" = 1;
#     }
#
# TB Display Mode = [1 = icon & text | 2 = icon only | 3 = text only]
# TB Icon Size Mode = [1] / I *think* this is legacy from when it had a big and small mode (<=10.7)
# TB Is Shown = [0|1] / whether the Finder window's Toolbar is shown or not
# TB Size Mode = [1] / I *think* this is legacy from when it had a big and small mode (<=10.7)
- name: setting Finder Toolbar pref's array via defaults
  command: {{ defaults_finder_write }} "NSToolbar Configuration Browser" -dict
    "TB Display Mode" "{{ toolbar_mode }}"
    "TB Icon Size Mode" "1"
    "TB Is Shown" "{{ toolbar_shown }}"
    "TB Size Mode" "1"


# changes made, now let's make them active
- name: killing and restarting Finder
  command: "/usr/bin/killall Finder > /dev/null 2>&1"
 