---
# Desktop's View Options, normally set via cmd-j in Finder
# playbook use:
#  - role: desktop_view_opts
#    arrange_by:
# [none|grid|name|kind|dateModified|dateCreated|dateLastOpened|dateAdded|size|label*]
# * 'label' is for 'Labels' in 10.8 and also 'Tags' in 10.9
#    grid_spacing: [0-100]
#    desktop_icon_size: [16-128]
#    label_on_bottom: [on|off]
#    show_icon_preview: [on|off]
#    show_item_info: [on|off]
#    text_size: [10-16]
#    toolbar_mode: [1-3]
#    toolbar_shown: [0|1]

# before we do anything, backup existing Finder preferences
- name: back up existing Finder prefs
  copy: "src={{ finder_plist }} dest=~/Library/Preferences/com.apple.finder.osxc_backup.plist mode=0600 backup=yes"


# explicity rewrite the array's dictionary:{
#    IconViewSettings =     {
#        arrangeBy = [none|grid|name|kind|dateModified|dateCreated|dateLastOpened|dateAdded|size|label];
#        backgroundColorBlue = 1;
#        backgroundColorGreen = 1;
#        backgroundColorRed = 1;
#        backgroundType = 0;
#        gridOffsetX = 0;
#        gridOffsetY = 0;
#        gridSpacing = [0-100];
#        iconSize = [16-128];
#        labelOnBottom = [0|1];
#        showIconPreview = [0|1];
#        showItemInfo = [0|1];
#        textSize = [10-16];
#        viewOptionsVersion = [0|1]; (only ever seen 1, once)
#    };
#}
- name: set Desktop Sort by to {{ arrange_by }}
  command: {{ defaults_finder_write }} DesktopViewSettings IconViewSettings -dict
    "arrangeBy" "{{ arrange_by }}"
    "backgroundColorBlue" "1"
    "backgroundColorGreen" "1"
    "backgroundColorRed" "1"
    "backgroundType" "0"
    "gridOffsetX" "0"
    "gridOffsetY" "0"
    "gridSpacing" "{{ grid_spacing }}"
    "iconSize" "{{ icon_size }}"
    "labelOnBottom" "{{ label_on_bottom }}"
    "showIconPreview" "{{ show_icon_preview }}"
    "showItemInfo" "{{ show_item_info }}"
    "textSize" "{{ text_size }}"
    "viewOptionsVersion" "0"


# explicitly rewrites the array's dictionary:
#     "NSToolbar Configuration Browser" =     {
#         "TB Display Mode" = [1|2|3];
#         "TB Icon Size Mode" = 1;
#         "TB Is Shown" = [0|1];
#         "TB Size Mode" = 1;
#     }
#
# TB Display Mode = [1 = icon & text | 2 = icon only | 3 = text only]
# TB Icon Size Mode = [1] / I *think* this is legacy from when it had a big and small mode (<=10.7)
# TB Is Shown = [0|1] / whether the Finder window's Toolbar is shown or not
# TB Size Mode = [1] / I *think* this is legacy from when it had a big and small mode (<=10.7)
- name: setting Finder Toolbar pref's array via defaults
  command: {{ defaults_finder_write }} "NSToolbar Configuration Browser" -dict
    "TB Display Mode" "{{ toolbar_mode }}"
    "TB Icon Size Mode" "1"
    "TB Is Shown" "{{ toolbar_shown }}"
    "TB Size Mode" "1"


# changes made, now let's make them active
- name: killing and restarting Finder
  command: "/usr/bin/killall Finder > /dev/null 2>&1"
 