---
# dump the current user image, notify the user, and then remove it
- name: Backing Up Current Image
  shell: "dscl . read /Users/{{ ansible_env.USER }} JPEGPhoto | tail +2 | xxd -r -p > /Users/{{ ansible_env.USER }}/Pictures/{{ ansible_env.USER}}_backup.jpg"

- name: Notify User of Backed Up Image
  debug: "msg='Your existing User Image was backed up to: /Users/{{ ansible_env.USER }}/Pictures/{{ ansible_env.USER}}_backup.jpg'"

- name: Deleting Existing Image
  command: "dscl . delete /Users/{{ ansible_env.USER }} JPEGPhoto"

# prepare user_image.txt and jpg, then dsimport and show it off
- name: Copy User Image Template
  template: "src=user_image.txt dest=/tmp/{{ ansible_env.USER }}.txt"

- name: Importing User Image via Import File
  command: "dsimport /tmp/{{ ansible_env.USER }}.txt /Local/Default M"

- name: "Opening Users & Group System Pref"
  command: open /System/Library/PreferencePanes/Accounts.prefpane