---
# downloads and installs munkitools from pkg or dmg
# various bits borrowed from http://munkibuilds.org/latest.sh
#
# requires ansible-playbook -K for sudo
# playbook use:
#  - role: munki
#    ## optional
#    update: [yes|no]
#    install_type: [pkg|dmg] (defaults to pkg)
#    ## defaults to http://munkibuilds.org/latest.[pkg|dmg]
#    munki_pkg_url: http://host.tld/munki.pkg
#    munki_dmg_url: http://host.tld/munki.dmg


- name: Determine if munki is already installed
  stat: path=/usr/local/munki follow=true
  register: munki_exists


- name: Acquire latest munki.pkg
  get_url: "url={{ munki_pkg_url }} dest=/tmp/munki.pkg"
  when: (update == true or munki_exists|failed) and install_type == "pkg"

- name: Install latest munki.pkg
  sudo: True
  command: "/usr/sbin/installer -pkg /tmp/munki.pkg -target /"
  when: (update == true or munki_exists|failed) and install_type == "pkg"

- name: Remove latest munki.pkg
  file: path=/tmp/munki.pkg state=absent
  when: (update == true or munki_exists|failed) and install_type == "pkg"


- name: Acquire latest munki.dmg
  get_url: "url={{ munki_dmg_url }} dest=/tmp/munki.dmg"
  when: (update == true or munki_exists|failed) and install_type == "dmg"

- name: Mount latest munki.dmg
  command: /usr/bin/hdiutil attach /tmp/munki.dmg -mountpoint /tmp/munki.XXXX
  when: (update == true or munki_exists|failed) and install_type == "dmg"

- name: Install latest from munki.dmg
  sudo: True
  shell: "/usr/sbin/installer -pkg /tmp/munki.XXXX/`/bin/ls /tmp/munki.XXXX/|grep munkitools` -target /"
  when: (update == true or munki_exists|failed) and install_type == "dmg"

- name: Unmount latest munki.dmg
  command: /usr/bin/hdiutil detach /tmp/munki.XXXX
  when: (update == true or munki_exists|failed) and install_type == "dmg"

- name: Remove latest munki.dmg
  file: path=/tmp/munki.dmg state=absent
  when: (update == true or munki_exists|failed) and install_type == "dmg"
