---
# tasks/main.yml

# install dependencies ?

- name: create saluser and salgroup
  sudo: True
  command: /usr/bin/dscl . {{ item }}
  with_items:
    - '-create /Groups/salgroup'
    - '-create /Groups/salgroup PrimaryGroupID "303"'
    - '-create /Users/saluser'
    - '-create /Users/saluser UserShell /bin/bash'
    - '-create /Users/saluser UniqueID "303"'
    - '-create /Users/saluser NFSHomeDirectory /usr/local/sal_env_path'
    - '-create /Users/saluser PrimaryGroupID "303"'

- name: git clone sal
  git: repo=https://github.com/grahamgilbert/sal.git
       dest={{ sal_env_path }}/sal

- name: ensure permissions of sal_env
  sudo: True
  file: path={{ sal_env_path }}
        owner=saluser
        group=salgroup 
        state=directory
        recurse=yes

#- name: check easy_install exists
#  stat: path=/usr/bin/easy_install
#  register: ez_install
 
- name: install pip via easy_install
  sudo: True
  easy_install: name=pip

#- name: install virtualenv via easy_install
#  easy_install: name=virtualenv

- name: pip install virtualenv 1.10.1
  sudo: True
  pip: name=virtualenv
       version=1.10.1
#       virtualenv={{ sal_env_path }}
#       virtualenv_site_packages=yes


- name: copy example_settings.py
  sudo: True
  copy: src={{ sal_settings_path }}/example_settings.py
        dest={{ sal_settings_path }}/settings.py

#- name: edit settings.py
#  sudo: True
#  lineinfile: dest={{ sal_settings_path }}/settings.py
#              regexp={{ item.regex }}
#              line={{ item.line }}
#  with_items:
#    - { regex: "Your Name"     , line: "('juan', 'juan@ninjabong.com')" }
#    - { regex: "^TIME_ZONE"    , line: "TIMEZONE = '{{ sal_timezone }}'" }
#    - { regex: "^DISPLAY_NAME" , line: "DISPLAY_NAME = {{ sal_display_name }}" }

- name: edit settings.py
  sudo: True
  lineinfile: dest={{ sal_settings_path }}/settings.py
              regexp='Your Name'
              line="     ('juan', 'juan@ninjabong.com')"

- name: edit settings.py 2
  sudo: True
  lineinfile: dest={{ sal_settings_path }}/settings.py
              regexp='^TIME_ZONE'
              line='TIME_ZONE = {{ sal_timezone }}'

- name: edit settings.py 3
  sudo: True
  lineinfile: dest={{ sal_settings_path }}/settings.py
              regexp='^DISPLAY_NAME'
              line='DISPLAY_ZONE = {{ sal_display_name }}'

- name: copy virtualenv wrapper
  sudo: True
  template: src=venv_exec.j2
            dest={{ sal_env_path }}/exec
            owner=saluser
            group=salgroup
            mode=0755

- name: pip install sal dependencies
  sudo: True
#  pip: requirements={{ sal_env_path }}/sal/setup/requirements.txt
#       virtualenv={{ sal_env_path }}
#       virtualenv_site_packages=yes
  command: "{{ sal_env_path }}/exec /usr/local/bin/pip install -r {{ sal_env_path}}/sal/setup/requirements.txt"

- name: do some stuff in virtualenv as saluser
  sudo: True
  command: "{{ sal_env_path }}/exec /usr/bin/python {{ sal_env_path }}/sal/manage.py {{ item }}"
  with_items:
    - "syncdb"
    - "migrate"
    - "collectstatic --noinput"

#- name: enable apache2's wsgi module
#  apache2_module: name=wsgi state=present

- name: pip install mod_wsgi
  sudo: True
  pip: name=mod_wsgi

- name: copy mod_wsgi to apache2 module's dir
  sudo: True
  copy: src=/Library/Python/2.7/site-packages/mod_wsgi/server/mod_wsgi-py27.so
        dest=/usr/libexec/apache2/mod_wsgi.so
        owner=root
        group=wheel
        mode=0755

- name: enable mod_wsgi module
  sudo: True
  lineinfile: dest=/private/etc/apache2/httpd.conf
              insertafter='LoadModule hfs_apple_module'
              line='LoadModule wsgi_module libexec/apache2/mod_wsgi.so'

#- name: enable apache2's wsgi module
#  sudo: True
#  apache2_module: name=wsgi state=present

- name: copy vhost template for apache2
  sudo: True
  template: src=sal.j2
            dest=/private/etc/apache2/other/sal.conf
            owner=root
            group=wheel
            mode=0644

# start/restart apache via handler
- name: (re)start apache2
  sudo: True
  command: /usr/sbin/apachectl restart
