---

- name: create saluser and salgroup for OS X
  sudo: True
  command: /usr/bin/dscl . {{ item }}
  with_items:
    - '-create /Groups/salgroup'
    - '-create /Groups/salgroup PrimaryGroupID "303"'
    - '-create /Users/saluser'
    - '-create /Users/saluser UserShell /bin/bash'
    - '-create /Users/saluser UniqueID "303"'
    - '-create /Users/saluser NFSHomeDirectory {{ sal_env_path }}'
    - '-create /Users/saluser PrimaryGroupID "303"'
  when: ansible_system == "Darwin"
