---
# Finder Window options
# playbook use:
#  - role: finder_window_opts
# - Menubar View Settings
#    window_style: [column|list|icon|coverflow]
#    column_width: ##
#    tab_bar: [on|off]
#    status_bar: [on|off]
#    path_bar: [on|off]
#    show_posix: [on|off]
# - Misc
#    quicklook_text_selection: [on|off]
#    menubar_transparency: [on|off]
#    icloud_as_default: [on|off]
#    toolbar_mode: 2


# before we do anything, backup existing Finder preferences
- name: back up existing Finder prefs
  copy: src={{ finder_plist }} dest=~/Library/Preferences/com.apple.finder.osxc_backup.plist mode=0600 backup=yes


# these are mostly setting via the Finder's menu > View
#
# default window view style
- name: set default Finder window view to column
  command: "{{ defaults_finder_write }} FXPreferredViewStyle -string clmv"
  when: window_style == "column"

- name: set width of columns to {{ column_width }}
  command: "{{ defaults_finder_write }} NSNavBrowserPreferedColumnContentWidth -int {{ column_width }}"
  when: window_style == "column"

- name: set default Finder window view to list
  command: "{{ defaults_finder_write }} FXPreferredViewStyle -string Nlsv"
  when: window_style == "list"

- name: set default Finder window view to icon
  command: "{{ defaults_finder_write }} FXPreferredViewStyle -string icnv"
  when: window_style == "icon"

- name: set default Finder window view to coverflow
  command: "{{ defaults_finder_write }} FXPreferredViewStyle -string Flwv"
  when: window_style == "coverflow"

# show Tabs bar, which only exists in 10.9+
- name: "set Tabs bar visibility to {{ tab_bar }}"
  command: "{{ defaults_finder_write }} ShowTabView -bool {{ tab_bar }}"
  when: "ansible_distribution_version | search('10.9')"

# show Status bar
- name: "set Status bar visibility to {{ status_bar }}"
  command: "{{ defaults_finder_write }} ShowStatusBar -bool {{ status_bar }}"

# show Path bar
- name: "set Path bar visibility to {{ path_bar }}"
  command: "{{ defaults_finder_write }} ShowPathbar -bool {{ path_bar }}"

# show POSIX path as Finder window title
- name: "set POSIX path as window title to {{ show_posix }}"
  command: "{{ defaults_finder_write }} _FXShowPosixPathInTitle -bool {{ show_posix }}"

# How to display the Finder Window Toolbar
# TB Display Mode = [1 = icon & text | 2 = icon only | 3 = text only]
# TB Icon Size Mode = [1] / I *think* this is legacy from when it had a big and small mode (<=10.7)
# TB Is Shown = [0|1] / whether the Finder windows Toolbar is shown or not, shameignored
# TB Size Mode = [1] / I *think* this is legacy from when it had a big and small mode (<=10.7)
#
# note: these are written as strings not numbers and "Is Shown" behaves as it pleases
#
- name: set Finder Toolbar prefs array via defaults
  command: '{{ defaults_finder_write }} "NSToolbar Configuration Browser" -dict
    "TB Display Mode" "{{ toolbar_mode }}"
    "TB Icon Size Mode" "1"
    "TB Is Shown" "1"
    "TB Size Mode" "1"'


# some misc things
- name: text selection in Quick Look
  command: "{{ defaults_finder_write }} QLEnableTextSelection -bool {{ quicklook_text_selection }}"

- name: menubar transparency
  command: "{{ defaults_global_write }} AppleEnableMenuBarTransparency -bool {{ menubar_transparency }}"

- name: iCloud as default save location
  command: "{{ defaults_global_write }} NSDocumentSaveNewDocumentsToCloud -bool {{ icloud_as_default }}"


# changes made, now let's make them active
- name: killing and restarting Finder
  command: "/usr/bin/killall Finder > /dev/null 2>&1"
 