---

- name: svn export googlefonts to ~/Library/Fonts
  subversion: "repo=https://github.com/w0ng/googlefontdirectory/trunk/fonts/{{ item }}/ dest=~/Library/Fonts/{{ item }} export=yes"
# ignore errors since svn will complain that dest 'is not a working copy'
  ignore_errors: True
  with_items: fonts
