---

accept_hostkey: no
bare: no
#depth: 1
dest: "{{ local_repo }}"
executable: /usr/bin/git
force: yes
#keyfile: None
recursive: yes
#reference: 
remote: origin
repo: "{{ remote_repo }}"
ssh_opts: None
update: yes
version: HEAD

local_repo: "{{ ansible_env.HOME }}/src/github.com/{{ remote_repo|basename }}"
remote_repo: "ssh://github.com/{{ ansible_user_id }}/xc-custom.git"
