---

- hosts: all

  roles:

  ## disable gatekeeper, enable locatedb and sshd, unhide ~/Library and set user account image
  - role: gatekeeper
    gatekeeper: disable
  - role: locatedb
    locatedb: load
  - role: sshd
    sshd: "on"
  - role: unhide_library
  - role: user_image
    image_name: ninjastar.jpg


  # install some ttf fonts
  - role: googlefonts
    fonts:
      - inconsolata
      - sourcecodepro

  # set some system volumes
  - role: systemprefs_sound
    alert_volume: "0.5"
    ui_soundfx: "1"
    volume_feedback: "0"

  # set the Computer Name
  - role: computername
    computername: VM-Yosemite

   # System Preferences - General
  - role: systemprefs_general
    system_appearance: graphite
    highlight_color: "1.000000 0.874510 0.701961"
    sidebar_icon_size: medium
    scrollbar: Automatic
    scroll_behavior: page
    close_confirms_changes: no
    restore_windows: no
    kb_ui_mode: all
    # only works for 10.10
    interface_style: Dark


  ## brew, then cask, then osx bits like the dock which need the cask to go first
  # brew stuff
  ## some old reliables
  - role: brew_package
    package_name: tree
  - role: brew_package
    package_name: htop-osx
  - role: brew_package
    package_name: homebrew/dupes/rsync
  ## wget
#  - role: brew_package
#    package_name: wget
  ## figlet!
#  - role: brew_package
#    package_name: figlet
  ## irc and silc
 # - role: brew_package
 #   package_name: irssi
 # - role: brew_package
 #   package_name: silc-client
  ## some networky stuffs
#  - role: brew_package
#    package_name: mtr
#  - role: brew_package
#    package_name: nmap
#  - role: brew_package
#    package_name: whatmask

  # cask stuff... for the apps
  ## Misc Stuff...
#  - role: cask_env_package
#    package_name: firefox
#    homebrew_cask_opts: --appdir=/Applications
  - role: cask_env_package
    package_name: google-chrome
    homebrew_cask_opts: --appdir=/Applications
#  - role: cask_env_package
#    package_name: music-manager
#  - role: cask_env_package
#    package_name: flip4mac
#  - role: cask_env_package
#    package_name: vlc
  ## Misc Things...
#  - role: cask_env_package
#    package_name: asepsis
#  - role: cask_env_package
#    package_name: box-sync
#  - role: cask_env_package
    package_name: flux
  - role: cask_env_package
    package_name: istat-menus
    homebrew_cask_opts: --appdir=/Applications
  - role: cask_env_package
    package_name: pacifist
    homebrew_cask_opts: --appdir=/Applications
#  - role: cask_env_package
#    package_name: totalterminal
#  - role: cask_env_package
#    package_name: osxfuse
#  - role: cask_env_package
#    package_name: sshfs
  ## Text Editors
#  - role: cask_env_package
#    package_name: atom
#  - role: cask_env_package
#    package_name: sublime-text
  - role: cask_env_package
    package_name: textmate
    homebrew_cask_opts: --appdir=/Applications
  ## VM related stuff
#  - role: cask_env_package
#    package_name: virtualbox
#  - role: cask_env_package
#    package_name: vmware-fusion
#  - role: cask_env_package
#    package_name: vagrant
  ## Panic, mmmmm Panic
#  - role: cask_env_package
#    package_name: transmit
#  - role: cask_env_package
#    package_name: panic-unison

  # osx config
  ## kill the dashboard
  - role: dashboard
    disabled: NO
  ## fix up the dock
#  - role: dock
#    apps:
#    - /Applications/"System Preferences.app"
#    - /Applications/Utilities/Terminal.app
#    - /Users/juan/Applications/"Google Chrome.app"
#    - /Users/juan/Applications/"Sublime Text 2.app"
#    - /Users/juan/Applications/TextMate.app
 #   - /Applications/Utilities/"Managed Software Update.app"
#    folders:
#    - path: ~/src/github.com
#      view: grid
#    - path: ~/Downloads
#      sort: datemodified
#      view: grid
