---
- hosts: all
  vars:
    # shared between: autopkg_install, munkitools, munki_repo and munki_manifest
    repo_path: /Users/Shared/munki_repo
    # shared between: munkitools and munki_client
    repo_url: http://{{ ansible_nodename }}/{{ repo_path | basename }}
    # shared between: munki_client and munki_manifest
    manifest_name: autopkg-osxc
    # shared between: autopkg_run and munki_manifest
    pkg_list: 
      - AdobeFlashPlayer
      - Firefox
      - GoogleChrome
      - Skype
      - TextMate2
      - TheUnarchiver
      - TotalTerminal
      - Transmit
      - Vagrant
      - VLC
#              MakeCatalogs
    # not shared, just autopkg_repo
    repos:
    # https://github.com/autopkg repos can be shortened, otherwise full url
    - "recipes"
    - "hjuutilainen-recipes"
    - "jps3-recipes"
    - "arubdesu-recipes"
    - "hansen-m-recipes"

  roles:
    - role: autopkg_install
    - role: autopkg_repo
    - role: autopkg_run
    - role: munki_manifest
#    - role: munki_iconimport
