---
- hosts: all
  roles:

  - role: ansible_vars
  - role: check_os_vers
  - role: computername
    computername: VM
  - role: git_config
    git_user_mail: ninja@ninjabong.com
    git_user_name: ninjabong
  - role: sshd
    sshd: "on"
